Prepare for release v2.3.0
elastic/apm-agent-go pull request #1405
Opened 2023-03-30 09:43 UTC by lahsivjar

2023-03-30 09:46 UTC, apmmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-go%2Fapm-agent-go-mbp%2FPR-1405/detail/PR-1405/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-go%2Fapm-agent-go-mbp%2FPR-1405/detail/PR-1405/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-go%2Fapm-agent-go-mbp%2FPR-1405/detail/PR-1405/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-go%2Fapm-agent-go-mbp%2FPR-1405/detail/PR-1405/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://apm-agent-go_1405.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/apm-ci/transactions/view?rangeFrom=2023-03-30T09:33:21.296Z&rangeTo=2023-03-30T09:53:21.296Z&transactionName=BUILD+apm-agent-go%2Fapm-agent-go-mbp%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=4fc8175ba2614b7ff718dfc63cbff7f1&transactionId=23e97566e5e74481)[![Snapshots](https://img.shields.io/badge/snapshots-artifacts-blue)](https://console.cloud.google.com/storage/browser/oblt-artifacts/apm-agent-go/PR-1405;tab=objects?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%257B_22k_22_3A_22Name%2520contains_22_2C_22t_22_3A10_2C_22v_22_3A_22_5C_513ddf5e_5C_22_22_2C_22i_22_3A_22displayName_22%257D%255D%22)))

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-03-30T09:43:21.296+0000


* Duration: 3 min 10 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `run benchmark tests` : Run the benchmark test.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-03-30 11:32 UTC, kruskall requested changes

2023-03-30 11:35 UTC, lahsivjar commented on CHANGELOG.asciidoc
> +==== 2.3.0 - 2022/03/30
Thanks 😄

2023-03-31 03:08 UTC, axw approved these changes

2023-03-31 03:08 UTC, axw commented on internal/apmgodog/go.mod
>  	go.elastic.co/apm/module/apmgrpc/v2 v2.1.0
```suggestion
	go.elastic.co/apm/module/apmgrpc/v2 v2.3.0
```

2023-03-31 03:30 UTC, merged