fix the same handlerFunc
elastic/apm-agent-go pull request #979
Opened 2021-06-22 11:39 UTC by woniu317

If one handlerFunc has been used for two or more routes, the transaction name is wrong.

2021-06-22 11:42 UTC, apmmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-go%2Fapm-agent-go-mbp%2FPR-979/detail/PR-979/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-go%2Fapm-agent-go-mbp%2FPR-979/detail/PR-979/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-go%2Fapm-agent-go-mbp%2FPR-979/detail/PR-979/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-go%2Fapm-agent-go-mbp%2FPR-979/detail/PR-979/1//artifacts) 

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats


* Build Cause: `Pull request #979 opened`


* Reason: `The PR is not allowed to run in the CI yet`


* Start Time: 2021-06-22T11:39:24.316+0000


* Duration: 3 min 7 sec


* Commit: 0d84bdb24a62a15715e05339f8a8e36fed4e2da7




#### Trends :test_tube:


![Image of Build Times](https://apm-ci.elastic.co/job/apm-agent-go/job/apm-agent-go-mbp/job/PR-979/buildTimeGraph/png)



</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->









### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-go%2Fapm-agent-go-mbp%2FPR-979/detail/PR-979/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Load a resource file from a shared library`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-go/pipelines/apm-agent-go-mbp/pipelines/PR-979/runs/1/steps/87/log/?start=0">here</a></li>
<li>Description: <code>approval-list/elastic/apm-agent-go.yml</code></l1>
</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-go/pipelines/apm-agent-go-mbp/pipelines/PR-979/runs/1/steps/90/log/?start=0">here</a></li>
<li>Description: <code>githubPrCheckApproved: The PR is not allowed to run in the CI yet. (Only users with write permissions can do so.)</code></l1>
</ul>
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2021-06-22T11:42:04.129Z]  > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
[2021-06-22T11:42:04.146Z]  > git config remote.origin.url git@github.com:elastic/apm-agent-go.git # timeout=10
[2021-06-22T11:42:04.154Z]  > git rev-parse --verify HEAD # timeout=10
[2021-06-22T11:42:04.158Z] No valid HEAD. Skipping the resetting
[2021-06-22T11:42:04.159Z]  > git clean -fdx # timeout=10
[2021-06-22T11:42:04.172Z] Fetching upstream changes from git@github.com:elastic/apm-agent-go.git
[2021-06-22T11:42:04.172Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-06-22T11:42:04.177Z]  > git fetch --no-tags --progress --prune -- git@github.com:elastic/apm-agent-go.git +refs/pull/979/head:refs/remotes/origin/PR-979 +refs/heads/master:refs/remotes/origin/master # timeout=15
[2021-06-22T11:42:04.847Z] Merging remotes/origin/master commit 8e97206077bfb879afde986455e3d15cc49f13e6 into PR head commit 0d84bdb24a62a15715e05339f8a8e36fed4e2da7
[2021-06-22T11:42:04.980Z] Merge succeeded, producing 0d84bdb24a62a15715e05339f8a8e36fed4e2da7
[2021-06-22T11:42:04.981Z] Checking out Revision 0d84bdb24a62a15715e05339f8a8e36fed4e2da7 (PR-979)
[2021-06-22T11:42:04.855Z]  > git config core.sparsecheckout # timeout=10
[2021-06-22T11:42:04.860Z]  > git checkout -f 0d84bdb24a62a15715e05339f8a8e36fed4e2da7 # timeout=15
[2021-06-22T11:42:04.932Z]  > git remote # timeout=10
[2021-06-22T11:42:04.941Z]  > git config --get remote.origin.url # timeout=10
[2021-06-22T11:42:04.949Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-06-22T11:42:04.953Z]  > git merge 8e97206077bfb879afde986455e3d15cc49f13e6 # timeout=10
[2021-06-22T11:42:04.970Z]  > git rev-parse HEAD^{commit} # timeout=10
[2021-06-22T11:42:04.984Z]  > git config core.sparsecheckout # timeout=10
[2021-06-22T11:42:04.991Z]  > git checkout -f 0d84bdb24a62a15715e05339f8a8e36fed4e2da7 # timeout=15
[2021-06-22T11:42:08.550Z] Commit message: "fix the same handlerFunc"
[2021-06-22T11:42:08.550Z] First time build. Skipping changelog.
[2021-06-22T11:42:08.550Z] Cleaning workspace
[2021-06-22T11:42:08.608Z]  > git --version # timeout=10
[2021-06-22T11:42:08.616Z]  > git --version # 'git version 2.17.1'
[2021-06-22T11:42:08.620Z] fatal: bad object bbed8ab717206e63fa6cc1cef7d35f4a13f717ab
[2021-06-22T11:42:09.257Z] Masking supported pattern matches of $JOB_GCS_BUCKET or $NOTIFY_TO
[2021-06-22T11:42:09.501Z] Timeout set to expire in 1 hr 0 min
[2021-06-22T11:42:09.542Z] The timestamps step is unnecessary when timestamps are enabled for all Pipeline builds.
[2021-06-22T11:42:08.553Z]  > git rev-parse --verify HEAD # timeout=10
[2021-06-22T11:42:08.560Z] Resetting working tree
[2021-06-22T11:42:08.560Z]  > git reset --hard # timeout=10
[2021-06-22T11:42:08.570Z]  > git clean -fdx # timeout=10
[2021-06-22T11:42:09.970Z] [INFO] Number of builds to be searched 10
[2021-06-22T11:42:10.172Z] [INFO] 'shallow' is forced to be disabled when running on PullRequests
[2021-06-22T11:42:10.201Z] Running in /var/lib/jenkins/workspace/agent-go_apm-agent-go-mbp_PR-979/src/go.elastic.co/apm
[2021-06-22T11:42:10.248Z] [INFO] gitCheckout: Checkout SCM PR-979 with some customisation.
[2021-06-22T11:42:10.295Z] [INFO] Override default checkout
[2021-06-22T11:42:10.376Z] Sleeping for 10 sec
[2021-06-22T11:42:20.398Z] The recommended git tool is: git
[2021-06-22T11:42:20.563Z] using credential f6c7695a-671e-4f4f-a331-acdce44ff9ba
[2021-06-22T11:42:20.573Z] Cloning the remote Git repository
[2021-06-22T11:42:20.588Z] Cloning repository git@github.com:elastic/apm-agent-go.git
[2021-06-22T11:42:20.612Z]  > git init /var/lib/jenkins/workspace/agent-go_apm-agent-go-mbp_PR-979/src/go.elastic.co/apm # timeout=10
[2021-06-22T11:42:20.620Z] Using reference repository: /var/lib/jenkins/.git-references/apm-agent-go.git
[2021-06-22T11:42:20.620Z] Fetching upstream changes from git@github.com:elastic/apm-agent-go.git
[2021-06-22T11:42:20.621Z]  > git --version # timeout=10
[2021-06-22T11:42:20.625Z]  > git --version # 'git version 2.17.1'
[2021-06-22T11:42:20.625Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-06-22T11:42:20.629Z]  > git fetch --tags --progress -- git@github.com:elastic/apm-agent-go.git +refs/heads/*:refs/remotes/origin/* # timeout=10
[2021-06-22T11:42:21.359Z]  > git config remote.origin.url git@github.com:elastic/apm-agent-go.git # timeout=10
[2021-06-22T11:42:21.363Z]  > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
[2021-06-22T11:42:21.369Z]  > git config remote.origin.url git@github.com:elastic/apm-agent-go.git # timeout=10
[2021-06-22T11:42:21.376Z] Fetching upstream changes from git@github.com:elastic/apm-agent-go.git
[2021-06-22T11:42:21.376Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-06-22T11:42:21.380Z]  > git fetch --tags --progress -- git@github.com:elastic/apm-agent-go.git +refs/pull/979/head:refs/remotes/origin/PR-979 +refs/heads/master:refs/remotes/origin/master # timeout=10
[2021-06-22T11:42:22.154Z] Checking out Revision 0d84bdb24a62a15715e05339f8a8e36fed4e2da7 (origin/PR-979)
[2021-06-22T11:42:22.229Z] Commit message: "fix the same handlerFunc"
[2021-06-22T11:42:22.244Z]  > git --version # timeout=10
 [...]

2021-06-23 01:57 UTC, axw commented
@woniu317 thanks for the PR! Can you please add a test illustrating the problem?

Also, we'll need you to [sign the CLA](https://www.elastic.co/contributor-agreement) before we can accept any contributions.

2021-06-23 02:23 UTC, woniu317 commented
> @woniu317 thanks for the PR! Can you please add a test illustrating the problem?
> 
> Also, we'll need you to [sign the CLA](https://www.elastic.co/contributor-agreement) before we can accept any contributions.

```
func TestMiddlewareTransportName(t *testing.T) {
	debugOutput.Reset()
	tracer, transport := transporttest.NewRecorderTracer()
	defer tracer.Close()

	e := gin.New()
	e.Use(apmgin.Middleware(e, apmgin.WithTracer(tracer)))
	e.GET("/hello/:name", handleHello)
	e.GET("/world/:name", handleHello)

	w := httptest.NewRecorder()
	req, _ := http.NewRequest("GET", "http://server.testing/hello/isbel", nil)
	req.Header.Set("User-Agent", "apmgin_test")
	req.RemoteAddr = "client.testing:1234"
	e.ServeHTTP(w, req)
	tracer.Flush(nil)

	payloads := transport.Payloads()
	transaction := payloads.Transactions[0]
	assert.Equal(t, "GET /hello/:name", transaction.Name)
}

func handleHello(c *gin.Context) {
	c.String(http.StatusOK, "Hello, %s!", c.Param("name"))
}

```

The request is '/hello/:name', but the transaction.Name is '/world/:name'.

2021-06-24 06:10 UTC, simitt commented
Thanks for the PR @woniu317. As my colleague mentioned, before we can accept the PR, can you please complete these two steps:
* sign the CLA
* add the testcase that you used for demonstrating the bug, to the code.

2021-06-24 07:52 UTC, woniu317 commented
> Thanks for the PR @woniu317. As my colleague mentioned, before we can accept the PR, can you please complete these two steps:
> 
> * sign the CLA
> * add the testcase that you used for demonstrating the bug, to the code.

The protocol has been signed. How to automatically associate with github?
![image](https://user-images.githubusercontent.com/9656502/123224186-26a70e80-d504-11eb-9eae-3bb425409aff.png)

2021-06-29 20:16 UTC, simitt commented
@woniu317 the CLA needs to be signed with the same user/email-address that what was used for the [commits](https://github.com/elastic/apm-agent-go/pull/979/commits). Is that also your user, in which case, could you please use that user to sign?

2021-06-30 07:04 UTC, simitt requested changes

2021-06-30 07:04 UTC, simitt commented on module/apmgin/middleware.go
> +	if _, ok := m.routeMap[requestName]; !ok {
Building on top of the proposed changes, the solution can be further simplified by removing the `routeMap` completely and only check that the `fullPath` is not empty; the map does not provide any adavantage any more when not using the handler. 
Something similar to 

```
	var requestName string
	if fullPath := c.FullPath(); fullPath != "" {
		requestName = c.Request.Method + " " + c.FullPath()
	} else {
		requestName = apmhttp.UnknownRouteRequestName(c.Request)
	}
```

2021-07-06 00:49 UTC, axw commented
@woniu317 in case it's not clear, you have commits associated with a different email address to the one that you used to sign the CLA:

![image](https://user-images.githubusercontent.com/843579/124527004-fda54880-de36-11eb-857f-1a597ebede47.png)

If you can squash and recreate those commits with your `woniu317` email/user, then the CLA checker should pass.

2021-07-06 01:21 UTC, woniu317 commented
see https://github.com/elastic/apm-agent-go/pull/983

2021-07-06 01:21 UTC, closed without merging